name: Run Main Dept Bot

on:
  schedule:
    # 0 = นาทีที่ 0 / 10 = 10:00 UTC (17:00 ไทย) / 1-5 = วันจันทร์ถึงศุกร์
    - cron: '0 10 * * 1-5' 
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests openpyxl

      - name: Execute Python Script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python main_rss_feed.py

      - name: Commit and Push Backup Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add Backup/
          git commit -m "Auto-update monthly backup (Main Dept)" || echo "No changes to commit"
          git pull --rebase origin main || echo "No rebase needed"
          git push origin main || echo "No push needed"
